### ISSUE TITLE
new version of Sysvinit 2.90

### ISSUE THREAD

**Issue by avmaisak** [emmett1/ports#119]
http://download.savannah.gnu.org/releases/sysvinit/sysvinit-2.90.tar.xz

but in the spkgbuild has patch sysvinit-2.89-consolidated-1.patch, and i have not checked yet compatibility with new version

**Comment by emmett1** [comment]
the old (sysvinit-2.89-consolidated-1.patch) is not compatible with sysvinit-2.90. but i made one here:
https://gist.github.com/emmett1/54d55ce9fe95145bb197214aae633d7d

you can test it out to see if it works. currently i'm using runit on my machine.

**Comment by avmaisak** [comment]
Today, has  been released new develpment version of LFS Book
Here is a patch by Bruce

https://gist.github.com/avmaisak/5b77200eff8ed63cc85315f1eaf6445e

**Comment by emmett1** [comment]
looks same as mine. anyway thats great, i will update it on my port collection.

**Comment by avmaisak** [comment]
Linux From Scratch - Version SVN-20180703 has been released. 
Sysvinit (2.90)  avaliable and in ports too
