### ISSUE TITLE
libffi configure options

### ISSUE THREAD

**Issue by avmaisak** [emmett1/ports#124]
from ticket http://wiki.linuxfromscratch.org/lfs/ticket/4303

From the mailing list ​http://lists.linuxfromscratch.org/pipermail/lfs-support/2018-June/052147.html suggests adding --with-gcc-arch=native to the libffi configuration.

We will need to check this out.

**Comment by emmett1** [comment]
hey, i'm sorry for late reply, got a bit busy week.

about this libffi configuration, i have read at the mailing list you gave and like bruce said, some people (including me) may transfer precompiled packages from a machine to another machine, so its not good option to add native to libffi configuration.

anyway i will wait updates from LFS pages.

**Comment by avmaisak** [comment]
I agree
